### PR TITLE
Better support CodeClimate and CircleCI

### PR DESCRIPTION
**Pull request by handerson**
Why?

Automated testing and code review are awesome

How?

* load masterpass key from env variable instead of file
* add code climate badges to readme
* add codeclimate codecoverage gem

### CODE REVIEW

**Comment by squaresurf** [comment]
Please fix the tests.

**Comment by handerson** [comment]
CircleCI is failing because I'm trying to load a multiline key into an environment variable (`MP_KEY`) in Circle, and a I apparently have no idea how to do that. I'm loading it into an env variable locally using dotenv, and it works fine.

Anyone have any ideas?

**Comment by squaresurf** [comment]
You can rerun the circle tests in ssh mode, then ssh in and play around with it.

**Comment by bbrock25** [comment]
:+1:

**Comment by samcdavid** [comment]
:+1:

**Pull request merged**
